# Predicting Interview Results Using Sound Data {#interview-prediction}

#### Keywords {-}

interview, supervised learning, sound data, prediction

## Post-Interview Frustration

Most interviewees have asked themselves this question after an interview: “Did I do well during the interview?” Some companies let you know the interview result right away, but most companies take at least a few days or even longer to respond to interviewees, who often become frustrated waiting for the result. If there were a way to predict interview results based on the conversation made during the interview, it would relieve interviewees’ frustration during the waiting period and help them emotionally prepare for the interview result.

## Prediction Using Interview Recording

Interview results could be predicted using machine learning methods and interview audio recording data. The basic idea is to identify different features from the audio data and to use supervised learning to predict the interview result. To train a machine learning model, a sufficient amount of recording data will need to be collected. To achieve this, a sample of job seekers will be selected from LinkedIn and will be asked to record their interviews and report interview results. Once the data is available, different features of the sound data should be identified. These features might include number of pauses, specific words used by interviewers, vibration level of the interviewee’s voice, etc. After the features are identified, the sound data will be processed and loaded into database with the identified features and interview results (Offer/No Offer) as columns and collected samples as rows. This data set will be then divided into a training set and test set and supervised learning methods such as logistic regression or decision trees will be used to create a model with job offer probability as the output. Once the model is trained and tested, a website can be created for interviewees to upload their interview recording and see the prediction result along with the analysis of different features. Once the interviewees find out their actual interview result, they will be asked to submit the result, which will then be used along with the originally uploaded recording to update the prediction model.

## Better Interview Experience

The solution described above will not only reduce post-interview frustration for interviewees, it can also help them identify the aspects of their interview style that can be improved using the analysis of different features. They can also perform practice interviews and analyze how certain changes can increase or decrease the probability of a job offer. It will be challenging to collect interview recording data mainly because of company compliance rules. However, if we can provide some analytics to companies as well as interviewees and collect data through a secured app to prevent data leakage, companies might be willing to record the interviews. The solution described will not completely free interviewees from frustration and uncertainty, but this will help improve overall interview experience for many job seekers by providing earlier insights from the interview data.
